server {
    listen 80;
    listen [::]:80;
    server_name tz.cyber-money.org;

    include /etc/nginx/snippets/tz-lite-cloudflare-real-ip.conf;
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type text/plain;
        try_files $uri =404;
    }
    location / {
        return 404;
    }
}
